name       : libcairo
version    : 1.14.12
release    : 33
source     :
    - https://www.cairographics.org/releases/cairo-1.14.12.tar.xz : 8c90f00c500b2299c0a323dd9beead2a00353752b2092ead558139bd67f7bf16
license    : LGPL-2.0
component  : desktop.library
summary    : cairo (2D graphics library)
description: |
    Cairo is a 2D graphics library with support for multiple output devices such as X, Quartz, Win32, image buffers, PS, PDF, and SVG.
emul32     : yes
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gl)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(pixman-1)
    - pkgconfig32(xcb-render)
    - pkgconfig32(xext)
    - pkgconfig32(xrender)
    - pkgconfig32(xshmfence)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
replaces   :
    - cairo
    - devel : cairo-devel
    - docs : cairo-docs
patterns   :
    - devel : /usr/bin
setup      : |
    %patch -p1 < $pkgfiles/cairo-modules.no-version.patch
    %patch -p1 < $pkgfiles/cairo-render-thin-lines.patch
    %patch -p1 < $pkgfiles/cairo-xlib-endianness.patch
    %reconfigure --disable-static \
        --disable-xlib-xcb \
        --enable-tee \
        --enable-gl \
        --enable-svg \
        --enable-ps \
        --enable-pdf \
        --enable-xcb \
        --enable-xli \
        --enable-ft \
        --enable-fc
build      : |
    %make
install    : |
    %make_install
