name       : libcairo
version    : 1.14.8
release    : 27
source     :
    - https://www.cairographics.org/releases/cairo-1.14.8.tar.xz : d1f2d98ae9a4111564f6de4e013d639cf77155baf2556582295a0f00a9bc5e20
license    :
    - LGPL-2.0
summary    : cairo (2D graphics library)
component  : desktop.library
builddeps  :
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(xrender)
    - pkgconfig32(xrender)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(libpng15)
    - pkgconfig32(libpng15)
    - pkgconfig(pixman-1)
    - pkgconfig32(pixman-1)
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - pkgconfig(freetype2)
    - pkgconfig32(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig32(fontconfig)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(xshmfence)
    - pkgconfig32(xcb-render)
    - pkgconfig32(zlib)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
replaces   :
    - cairo
    - devel : cairo-devel
    - docs : cairo-docs
patterns   :
    - devel : /usr/bin
description: |
    Cairo is a 2D graphics library with support for multiple output devices such as X, Quartz, Win32, image buffers, PS, PDF, and SVG.
setup      : |
    %patch -p1 < $pkgfiles/cairo-modules.no-version.patch
    %patch -p1 < $pkgfiles/cairo-render-thin-lines.patch
    %patch -p1 < $pkgfiles/cairo-xlib-endianness.patch
    autoreconf -vfi
    %configure --disable-static \
               --prefix=/usr \
               --disable-xlib-xcb \
               --enable-tee \
               --enable-gl \
               --enable-svg \
               --enable-ps \
               --enable-pdf \
               --enable-xcb \
               --enable-xli \
               --enable-ft \
               --enable-fc
build      : |
    %make
install    : |
    %make_install
