name       : libcairo
version    : 1.14.6
release    : 26
source     :
    - http://cairographics.org/releases/cairo-1.14.6.tar.xz : 613cb38447b76a93ff7235e17acd55a78b52ea84a9df128c3f2257f8eaa7b252
license    :
    - LGPL-2.0
summary    : cairo (2D graphics library)
builddeps  :
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - pkgconfig(xrender)
    - pkgconfig32(xrender)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(libpng15)
    - pkgconfig32(libpng15)
    - pkgconfig(pixman-1)
    - pkgconfig32(pixman-1)
    - pkgconfig(gl)
    - pkgconfig32(gl)
    - pkgconfig(freetype2)
    - pkgconfig32(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig32(fontconfig)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(xshmfence)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
replaces   :
    - cairo
    - devel : cairo-devel
    - docs : cairo-docs
patterns   :
    - devel : /usr/bin
description: |
    Cairo is a 2D graphics library with support for multiple output devices such as X, Quartz, Win32, image buffers, PS, PDF, and SVG.
setup      : |
    %patch -p1 < $pkgfiles/cairo-modules.no-version.patch
    %patch -p1 < $pkgfiles/cairo-render-thin-lines.patch
    %patch -p1 < $pkgfiles/cairo-xlib-endianness.patch
    autoreconf -vfi
    %configure --disable-static \
               --prefix=/usr \
               --disable-xlib-xcb \
               --enable-tee \
               --enable-gl \
               --enable-svg \
               --enable-ps \
               --enable-pdf \
               --enable-xcb \
               --enable-xli \
               --enable-ft \
               --enable-fc
build      : |
    %make
install    : |
    %make_install
