name       : libcairo
version    : 1.17.4
release    : 50
source     :
    - https://cairographics.org/snapshots/cairo-1.17.4.tar.xz : 74b24c1ed436bbe87499179a3b27c43f4143b8676d8ad237a6fa787401959705
license    : LGPL-2.1-or-later
component  : desktop.library
homepage   : https://cairographics.org/
summary    : cairo (2D graphics library)
description: |
    Cairo is a 2D graphics library with support for multiple output devices such as X, Quartz, Win32, image buffers, PS, PDF, and SVG.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gl)
    - pkgconfig32(glib-2.0)
    - pkgconfig32(pixman-1)
    - pkgconfig32(xcb-render)
    - pkgconfig32(xext)
    - pkgconfig32(xrender)
    - pkgconfig32(xshmfence)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
    - gtk-doc
replaces   :
    - cairo
    - devel : cairo-devel
    - docs : cairo-docs
patterns   :
    - devel : /usr/bin
setup      : |
    %apply_patches
    %reconfigure --disable-static \
        --disable-symbol-lookup \
        --disable-xlib-xcb \
        --enable-fc \
        --enable-ft \
        --enable-gl \
        --enable-pdf \
        --enable-png \
        --enable-ps \
        --enable-svg \
        --enable-tee \
        --enable-xcb \
        --enable-xli
build      : |
    %make
install    : |
    %make_install
