name       : libcairo
version    : 1.15.12
release    : 38
source     :
    - https://www.cairographics.org/snapshots/cairo-1.15.12.tar.xz : 7623081b94548a47ee6839a7312af34e9322997806948b6eec421a8c6d0594c9
license    : LGPL-2.0
component  : desktop.library
summary    : cairo (2D graphics library)
description: |
    Cairo is a 2D graphics library with support for multiple output devices such as X, Quartz, Win32, image buffers, PS, PDF, and SVG.
emul32     : yes
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gl)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(pixman-1)
    - pkgconfig32(xcb-render)
    - pkgconfig32(xext)
    - pkgconfig32(xrender)
    - pkgconfig32(xshmfence)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
replaces   :
    - cairo
    - devel : cairo-devel
    - docs : cairo-docs
patterns   :
    - devel : /usr/bin
setup      : |
    %apply_patches
    %reconfigure --disable-static \
        --disable-xlib-xcb \
        --enable-tee \
        --enable-gl \
        --enable-svg \
        --enable-ps \
        --enable-pdf \
        --enable-xcb \
        --enable-xli \
        --enable-ft \
        --enable-fc
build      : |
    %make
install    : |
    %make_install
