name        : libcairo
version     : 1.14.4
release     : 22
source     :
    - http://cairographics.org/releases/cairo-1.14.4.tar.xz : f6ec9c7c844db9ec011f0d66b57ef590c45adf55393d1fc249003512522ee716
license     :
    - LGPL-2.0
summary     : cairo (2D graphics library)
builddeps   :
    - pkgconfig(x11)
    - pkgconfig(xrender)
    - pkgconfig(xext)
    - pkgconfig(libpng15)
    - pkgconfig(pixman-1)
    - pkgconfig(gl)
    - pkgconfig(freetype2)
replaces    :
    - cairo
    - devel: cairo-devel
    - docs: cairo-docs
patterns    :
    - devel: /usr/bin
description : |
    Cairo is a 2D graphics library with support for multiple output devices such as X, Quartz, Win32, image buffers, PS, PDF, and SVG.
setup      : |
    %patch -p1 < $pkgfiles/cairo-modules.no-version.patch
    %patch -p1 < $pkgfiles/cairo-render-thin-lines.patch
    %patch -p1 < $pkgfiles/cairo-xlib-endianness.patch
    autoreconf -vfi
    %configure --disable-static \
               --disable-xlib-xcb \
               --enable-tee \
               --enable-gl \
               --enable-svg \
               --enable-ps \
               --enable-pdf \
               --enable-xcb \
               --enable-xli \
               --enable-fc \
               --enable-ft \
               --disable-lto
build      : |
    %make
install    : |
    %make_install
